ALTER TABLE "BAGS" ADD COLUMN "TITLE" varchar(100);

UPDATE "BAGS" SET "TITLE"='Title 1' WHERE "ID"=1;
UPDATE "BAGS" SET "TITLE"='Title 2' WHERE "ID"=2;
UPDATE "BAGS" SET "TITLE"='Title 3' WHERE "ID"=3;